version: '2'
services:
  user_managment:
    build: ./backend
    environment:
      DATABASE_CONNECTION_URL: mysql://root:root@mysqldb:3306/user_managment
      MYSQL_HOST: mysqldb
      NODE_ENV: production
      MYSQL_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    links:
      - mysqldb:mysqldb
    depends_on:
      - mysqldb
    ports:
      - "3000:3000"

  mysqldb:
    image: mysql
    environment:
      MYSQL_DATABASE: user_managment
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306"
